### ISSUE TITLE
Version control for `/docs`?

### ISSUE THREAD

**Issue by mondras** [actuallymentor/sandbox-website#22]
Just a question: why are we keeping under version control the `/docs` folder? isn't that supposed to be the build? I see the folder is in the`.gitignore` file and to me it makes sense to keep it out of version control.

**Comment by actuallymentor** [comment]
The `/docs` folder needs to be committed since that is what the Github Pages system serves. The reason it is in `.gitignore` is so that people who do PRs only commit `/src` code, after the PR one of those with write access runs `npm run deploy`

**Comment by mondras** [comment]
Oh! I didn't know we used github pages, interesting. 

Still, having them on `.gitignore` is useless since changes are actually being tracked as per below. I was reading a bit on github pages, looks like they use Jekyll as a build system and not Pug. I guess as long as no one else is committing the files the approach works but I feel it doesn't feel clean. It's a minor thing tbh, I you feel we're ok we can close this.

```
→ git status
On branch add-GA-code
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
        modified:   docs/about.html
        modified:   docs/bylaws.html
        modified:   docs/contact.html
        modified:   docs/donation.html
        modified:   docs/faq.html
        modified:   docs/history.html
        modified:   docs/index.html
        modified:   docs/join.html
        modified:   docs/js/app.js
        modified:   docs/js/app.js.map
        modified:   docs/manifesto.html
        modified:   docs/media.html
        modified:   docs/members.html
        modified:   docs/oncommunity.html
        modified:   docs/slack.html
        modified:   docs/store.html```

**Comment by actuallymentor** [comment]
Github pages doesn't use a build system, it simply serves the folder statically. Many people use Jekyll, but we don't since we use a webpack based build with pug.

It's weird that is tracks them, the `.gitignore` should result in it, well, ignoring the folder.

**Comment by actuallymentor** [comment]
> Oh! I didn't know we used github pages, interesting.

With all the chaos on who manages what with hosting etc I decided to just run it on GH. Nice and simple. We don't need any backend so it server perfectly.

> Still, having them on .gitignore is useless since changes are actually being tracked as per below.

That is weird, it should just ignore them... You using `git add` with the `-f` flag?

>  reading a bit on github pages, looks like they use Jekyll as a build system and not Pug

Github pages is just a static folder serving mechanism for us. It supports Jekyll but we build the html from the pug ourselves so that is not relevant as such.

> I guess as long as no one else is committing the files the approach works but I feel it doesn't feel clean

I mean, ideally we have a CI tool do the build and deploy, but I tried to keep things as simple as possible :)

Right now the flow is: 1) PR edits to /src 2) after merge run `npm run build` to commit the new `docs` files.

**Comment by mondras** [comment]
Thanks a lot for the clarification! Using gh pages makes a lot of sense with our chaos. 

Did you see this? https://github.com/features/actions

I’m gonna give it a try and that might do exactly what we need! I’ll create a new PR once it works. 

Also lmk if there’s anything more pressing you need help with.

**Comment by actuallymentor** [comment]
Interesting, seems like a fun beta feature to try. Looking forward to
seeing the PR!

Nothing very pressing on my end.

Actually the actions might solve some issues like more frequent mailchimp
profile updates.

**Comment by mondras** [comment]
Right, I'll take a stab whenever github actions are out.

So mailchimp is our main database? I saw some slack handles where actually the members addresses, not sure if they are ok exposing them publicly? What's the issue with the updates right now?

I remember @mmayernick has been using airtable for other sandbox things, might be nice to standardize but I guess you rely on mailchimp for the newsletter.

**Comment by andremalan** [comment]
There is also space for splitting out the information, I think we need a source of truth for who is a member (could be MailChimp), but for things like profile information that could be separated somewhere else, where it's easier to update.

**Comment by actuallymentor** [comment]
> So mailchimp is our main database?

Yes.

> I saw some slack handles where actually the members addresses

That would be their own input mistakes...

> What's the issue with the updates right now?

I run them manually once a week or so but I tend to forget. Really it is just as simple as `npm run member-update`.

> I remember @mmayernick has been using airtable for other sandbox things, might be nice to standardize but I guess you rely on mailchimp for the newsletter.

Not for member data I think.

> for things like profile information that could be separated somewhere else, where it's easier to update.

The reason it's mailchimp now is 1) the data is already there and 2) it doesn't require maintaining a new backend/app/service.

**Comment by mondras** [comment]
A couple ideas, let me know your thoughts:

1. Separate the members database from the repository and keep it on a public S3 bucket. We can easily have a daily/weekly cron job that updates it (happy to run it in one of my personal servers or we could set up a sandbox AWS account and trigger this using a lambda function).

2. Keep mailchimp as the source of truth

3. Notify members that have public-facing email addresses that we need them to update them, but question: how can members update this data?

4. We can set up a CI service that keeps the built pages on a `gh-pages` and keep the main repo for just the sources. We can also set it up so that whenever we do a merge to master the website is re-deployed. Or we could also move the actual pages to the sandbox AWS account, serve via S3 and manage the domain from there as well.

Anyway, lmk what you think!

**Comment by actuallymentor** [comment]
> Separate the members database from the repository and keep it on a public S3 bucket.

Why on S3 and not GH? There should be no difference if we are using both to statically serve it.

> Keep mailchimp as the source of truth

Cool with me, less backend to maintain is less headache.

> Notify members that have public-facing email addresses that we need them to update them

Good.

> But question: how can members update this data?

Every newsletter has a 'update your profile' link for that specific person.

> We can set up a CI service that keeps the built pages on a gh-pages branch and keep the main repo for just the sources.

Sounds elegant, though I'm not able to commit time to setting it up.

> We can also set it up so that whenever we do a merge to master the website is re-deployed.

Both work for me.

> Or we could also move the actual pages to the sandbox AWS account, serve via S3 and manage the domain from there as well.

I'm not against AWS, but not exactly for it either. It adds another layer of complexity, specifically from a management perspective. If you & me go offline for a month or 2 nobody will have the access and/or expertise to do anything to the website.

**Comment by mondras** [comment]
> Why on S3 and not GH? There should be no difference if we are using both to statically serve it.

We wouldn't need to be adding commits to the codebase with each change, keeping data and code separated. Plus we can set up a separate process to weekly / daily update the members database from mailchimp. This process wouldn't need to be pushing into the repository.

> I'm not against AWS, but not exactly for it either. It adds another layer of complexity, specifically from a management perspective. If you & me go offline for a month or 2 nobody will have the access and/or expertise to do anything to the website.

I feel you here, we should strive to keep things as simple as possible. Yet that issue you mention is an issue today: e.g. we can't fix HTTPS because who know who owns the domain, if you were to be gone admin of this repo would be up in the air, etc.

I've already notified members with emails exposed to check their data if they care about it.

I think you guys have done a great job on getting things up and running! I'm grateful for all the effort here :)
