### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mondras** [actuallymentor/sandbox-website#23]
Happy to help serve the page via HTTPS!

**Comment by actuallymentor** [comment]
I see there is a https issue, [this is the GH help page](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors) for it.

I have no control over the DNS, if you can figure out what we need to change we can track down the domain owner.

**Comment by ryanseys** [comment]
Yeah, you'll need to update the DNS settings for `sandbox.is` to point `A` records to the following IP addresses:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

instead of `192.30.252.153` and `192.30.252.154` which is what they are currently set to.

You can see this via:

```sh
$ dig sandbox.is +nostats +nocomments +nocmd

...
sandbox.is.		1654	IN	A	192.30.252.153
sandbox.is.		1654	IN	A	192.30.252.154
```

So the question is, who controls `sandbox.is`? We could email `info@sandbox.is` and find out 😄

**Comment by ryanseys** [comment]
I just emailed `info@sandbox.is` so we will see what happens :)

**Comment by Lucjodet** [comment]
I can already tell you that nothing will happen. We do not have access to this email account. I am in process with Goggle to regain access. 

Luc

---------------------------------------------
Luc Jodet
 
Tel. (Swiss)     +41 79 825 27 26
Tel. (French)   +33 7 62 45 96 65
Skype              lucjodet
Twitter            @lucjodet
---------------------------------------------

**Comment by ryanseys** [comment]
I work at Google so let me know if there's some way I can help :)

**Comment by mmayernick** [comment]
@actuallymentor previously mentioned that: "The domain owner/manager is currently Christophe (support-fbs@ebrandservices.com)."

**Comment by actuallymentor** [comment]
> @actuallymentor previously mentioned that: "The domain owner/manager is currently Christophe ([support-fbs@ebrandservices.com](mailto:support-fbs@ebrandservices.com))."

I double checked and indeed this is still true.

@mmayernick is this a good time to transfer that asset to board control? Or do you not think the legal entity is not suitable?

**Comment by Lucjodet** [comment]
Hello Everyone,

We finally recovered the Google admin account. 

I rest the password to info@sandbox.is <mailto:info@sandbox.is>. Who needs access to that mailbox? If you do send me email to luc@sandbox.is <mailto:luc@sandbox.is>.

Happy Holidays!

Luc

---------------------------------------------
Luc Jodet
 
Tel. (Swiss)     +41 79 825 27 26
Tel. (French)   +33 7 62 45 96 65
Skype              lucjodet
Twitter            @lucjodet
---------------------------------------------

**Comment by actuallymentor** [comment]
@Lucjodet I'd like to get DNS access to resolve this issue. Do you have it?

**Comment by actuallymentor** [comment]
SSL support added. Should work now.
